### PR TITLE
WIP - Various changes and refactoring

### PR DESCRIPTION
**Pull request by mrkkrp**

### CODE REVIEW

**Comment by lpaulmp** [comment]
@mrkkrp LGTM

**Review by lpaulmp — APPROVED** [review]

**Comment by mrkkrp** [comment]
@lpaulmp Forgot to specify that it's WIP. This is only begginning!

**Comment by lpaulmp** [comment]
@mrkkrp no problem

**Comment by sestrella** [comment]
@mrkkrp LGTM

**Pull request merged**
