### PR TITLE
Add missing modules

### PR DESCRIPTION
**Pull request by sestrella**

### CODE REVIEW

**Comment by sestrella** [comment]
@jsantos17 @jsl @juanpaucar could you guys take a look please

**Comment by jsl** [comment]
Should those be exposed, or other modules?

**Comment by sestrella** [comment]
@jsl I think you're right, those should be `other_modules` since they are used to read the default configuration internally

**Comment by sestrella** [comment]
@jsl I pushed some changes, would you mind taking a look please

**Comment by jsl** [comment]
LGTM, thanks!

**Pull request merged**
